version: "3.5"

services:
  mysql:
    container_name: mysql
    tty: true
    ports:
      - "3360:3308"
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - final_work
    volumes:
      - ./data:/var/lib/mysql
  redis: 
    container_name: redis
    tty: true
    image: 'redis:7.2'
    ports:
      - 6379:6378
    networks:
      - final_work
  php:
    container_name: php
    build: ./php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./app:/var/www/
    networks:
      - final_work
networks:
    final_work:
      name: final_work

      


